version: "3.9"

services:

  db:
    image: postgres:latest
    container_name: db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - env/db_variables.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 1s
      retries: 10
      timeout: 10s

  web:
    build: .
    container_name: web
    command: bash -c "python src/manage.py makemigrations && python src/manage.py migrate && python src/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/src
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - env/web_variables.env
      - env/db_variables.env
    stdin_open: true
    tty: true

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./nginx:/etc/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    logging:
      driver: none
